name: eut
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - blas=1.0
  - ca-certificates=2020.1.1
  - certifi=2019.11.28
  - cycler=0.10.0
  - freetype=2.9.1
  - icu=58.2
  - intel-openmp=2020.0
  - jpeg=9b
  - kiwisolver=1.0.1
  - libpng=1.6.37
  - matplotlib=3.1.3
  - matplotlib-base=3.1.3
  - mkl=2019.5
  - mkl-service=2.3.0
  - mkl_fft=1.0.15
  - mkl_random=1.1.0
  - numpy=1.18.1
  - numpy-base=1.18.1
  - openssl=1.1.1
  - pandas=1.0.1
  - pip=20.0.2
  - pyparsing=2.4.6
  - pyqt=5.9.2
  - python=3.8.1
  - python-dateutil=2.8.1
  - pytz=2019.3
  - qt=5.9.7
  - scipy=1.4.1
  - setuptools=45.2.0
  - sip=4.19.13
  - six=1.14.0
  - sqlite=3.31.1
  - tornado=6.0.3
  - wheel=0.34.2
  - zlib=1.2.11
