name: eut
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - matplotlib=3.1.3
  - matplotlib-base=3.1.3
  - numpy=1.18.1
  - pandas=1.0.1
  - pip=20.0.2
  - python=3.8.1
  - scipy=1.4.1
